website/celestini/urls.py
from django.urls import path,include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    path('home/', include('home.urls')),
]

website/home/urls.py
from django.urls import path,include
from .views import *

app_name='home'
urlpatterns = [
    path('maps/', get_maps,name='maps'),
    path('details/<string>', get_details,name='details'),
    path('', home_page,name='home'),
]

website/home/models.py
from django.db import models
from django.utils import timezone


class pollutants(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    pm25 = models.FloatField(null=True, blank=True)
    pm10 = models.FloatField(null=True, blank=True)
    no2 = models.FloatField(null=True, blank=True)
    so2 = models.FloatField(null=True, blank=True)
    co = models.FloatField(null=True, blank=True)
    temp = models.FloatField(null=True, blank=True)
    hum = models.FloatField(null=True, blank=True)
    location = models.CharField(max_length=100)

    def __str__(self):
        return str(self.date)

class concPollutant(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    pm25 = models.FloatField(null=True, blank=True)
    pm10 = models.FloatField(null=True, blank=True)
    no2 = models.FloatField(null=True, blank=True)
    so2 = models.FloatField(null=True, blank=True)
    co = models.FloatField(null=True, blank=True)
    temp = models.FloatField(null=True, blank=True)
    o3 = models.FloatField(null=True, blank=True)
    hour = models.IntegerField(null=True, blank=True)
    month = models.IntegerField(null=True, blank=True)
    location = models.CharField(max_length=100)

    def __str__(self):
        return str(self.date)

class classPollutant(models.Model):
    date = models.DateTimeField()
    pm25 = models.IntegerField(null=True, blank=True)
    so2 = models.IntegerField(null=True, blank=True)
    no2 = models.IntegerField(null=True, blank=True)
    pm10 = models.IntegerField(null=True, blank=True)
    location = models.CharField(max_length=100)
    def __str__(self):
        return str(self.date)

class regrPollutant(models.Model):
    date = models.DateTimeField()
    pm25 = models.IntegerField(null=True, blank=True)
    so2 = models.IntegerField(null=True, blank=True)
    no2 = models.IntegerField(null=True, blank=True)
    pm10 = models.IntegerField(null=True, blank=True)
    location = models.CharField(max_length=100)

    def __str__(self):
        return str(self.date)

website/home/views.py
from django.shortcuts import render
import requests, json, time
from django.http import JsonResponse
from firebase import firebase
import urllib
from bs4 import BeautifulSoup
from .models import pollutants, classPollutant, regrPollutant
from oauth2client.client import GoogleCredentials
from googleapiclient import discovery
import socket
import numpy as np
from django.db.models import Q

def home_page(request):
  return render(request, 'home/home.html')


def get_maps(request):
  entries = pollutants.objects.all()
  return render(request, 'home/map.html', context={'pollutants': entries})

def get_details(request,string):
  entries = pollutants.objects.filter(Q(location=string))
  classes = classPollutant.objects.filter(Q(location=string))
  predictions = regrPollutant.objects.filter(Q(location=string))
  return render(request,
                  "home/details.html",
                  context={'place':string, 'pollutants': entries, "classes": classes, "predictions": predictions})

website/templates/base.html
{% load pwa %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
		{% progressive_web_app_meta %}
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>{% block title %}Pollution{% endblock %}</title>
	<!-- Bootstrap -->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<link rel = 'stylesheet' href="{% static 'home/base.css' %}">
	<link rel="stylesheet" href="{% static 'home/home.css' %}">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"/>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'home/base.css' %}"/>

	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<link rel="stylesheet" href="{% static 'home/home.css' %}">
	<link rel="manifest" href="{% static 'manifest.json' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">


	{% block styles %}
	{% endblock %}
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<script src="https://d3js.org/d3.v4.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
	<!-- jQuery -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
	<script src="assets/js/browser.min.js"></script>
	<script src="https://github.com/thecreation/breakpoints-js/blob/master/dist/breakpoints.min.js"></script>
	<script src="assets/js/util.js"></script>
	<script src="assets/js/main.js"></script>
	<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
	<script src="https://openlayers.org/en/v4.6.5/build/ol.js"></script>

	<script>

		document.addEventListener("DOMContentLoaded", function(){
			$('.preloader-background').delay(1700).fadeOut('slow');

			$('.preloader-wrapper')
				.delay(1700)
				.fadeOut();
		});
		$(document).ready(function() {
		$('.preloader-background').delay(1700).fadeOut('slow');

			$('.preloader-wrapper')
				.delay(1700)
				.fadeOut();
		});

	</script>
	<style>
.preloader-background {
	display: flex;
	align-items: center;
	justify-content: center;
	background-color: #eee;

	position: fixed;
	z-index: 100;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;	
}

body {
	background-image: url("{% static 'home/images/dust_scratches.png' %}");
	background-repeat:repeat;
}
	</style>
	</head>
	<body {% block body_style %} {% endblock %}>
		<div class="preloader-background">
			<div class="preloader-wrapper big active">
				<div class="spinner-layer spinner-green-only">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div>
					<div class="gap-patch">
						<div class="circle"></div>
					</div>
					<div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>
			</div>
		</div>

		<nav style="background-color:#23a15f;background: linear-gradient(70deg,#23a15f,#00a79b);">
			<div class="nav-wrapper">
				<a href="{% url 'home:home' %}" class="brand-logo">CLair</a>
				<a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
				<ul class="right hide-on-med-and-down">
					<li {% if request.resolver_match.url_name == "home" %}class="active"{% endif %}><a href="{% url 'home:home' %}">Home</a></li>
					<li {% if request.resolver_match.url_name == "maps" %}class="active"{% endif %}><a href="{% url 'home:maps' %}">Map</a></li>
				</ul>
			</div>
		</nav>

		<ul class="sidenav" id="mobile-demo">
			<li {% if request.resolver_match.url_name == "home" %}class="active"{% endif %}><a href="{% url 'home:home' %}">Home</a></li>
			<li {% if request.resolver_match.url_name == "maps" %}class="active"{% endif %}><a href="{% url 'home:maps' %}">Map</a></li>
		</ul>
		<script>
			document.addEventListener('DOMContentLoaded', function() {
				var elems = document.querySelectorAll('.sidenav');
				var instances = M.Sidenav.init(elems, options);
			});

// Or with jQuery

$(document).ready(function(){
	$('.sidenav').sidenav();
});
		</script>
		<div id = "content">
			{% block content %}{% endblock %}
		</div>

		<footer class="page-footer footer-fixed " style="background-color:#00a79b; background: linear-gradient(70deg,#00a79b,#23a15f);bottom:0;left:0;width:100%;">
			<div class="container" style="padding-bottom:20px;background-color:#00a79b; background: linear-gradient(70deg,#00a79b,#23a15f">
				<center> © 2018 Copyright Celestini Team India </center>
			</div>
		</footer>
	</body>
	<script type="text/javascript">
		$('.sidenav').sidenav();
	</script>
</html>

website/templates/home/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<body class="is-preload">
  <!-- Banner -->
  <iframe class="z-depth-2" width=100% height="450" src="https://www.youtube.com/embed/e6rglsLy1Ys" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen style="margin-left:auto;margin-right:auto;"></iframe>
  <!-- Highlights -->

  <section "wrapper" >
    <div>
	    <div>
      <header class="special" style="padding-top:20px;padding-bottom:50px;">
        <h2 style="color:#00a79b;">About us</h2>
        <p>The web application has been developed for you in collaboration with IIT Delhi and Marconi Society.
        We decided to take advantage of our knowledge and experience to create a top-quality application that clearly 
        displays air pollution data from around the Delhi and allows you to monitor pollution for any part of Delhi.</p>
      </header>
     </div>
      <div style="background-color:#23a15f;background: linear-gradient(70deg,#23a15f,#00a79b); padding-top:10px;">
        <h2 style="color:white;"><center>Facts</center></h2>
        <div class="highlights " style="padding-left:30px;padding-right:30px;padding-bottom:60px;">
          <section>
            <div class="content" style="background-color:white;">
              <data style="font-size:80px;font-family:Roboto,sans-serif;font-weight:900;width:263px;letter-spacing: -9px;color:#bf272d">10 k+</data>
              <blockquote style="font-family:Roboto;font-size:24px;line-height:24px;">Pollution related Death toll/year.</blockquote>
            </div>
          </section>
          <section>
            <div class="content" style="background-color:white;">
              <data style="font-size:80px;font-family:Roboto,sans-serif;font-weight:900;width:263px;letter-spacing: -7px;color:#bf272d">44%</data>
              <blockquote style="font-family:Roboto;font-size:24px;line-height:24px;">Of Delhi school children have reduced lung function compared to other Indian cities.</blockquote>
            </div>
          </section>
          <section>
            <div class="content" style="background-color:white;">
              <data style="font-size:80px;font-family:Roboto,sans-serif;font-weight:900;width:263px;letter-spacing: -7px;color:#bf272d">2015</data>
              <blockquote style="font-family:Roboto;font-size:24px;line-height:24px;">WHO ranked Delhi as most polluted city.</blockquote>
            </div>
          </section>
          <section>
            <div class="content" style="background-color:white;">
              <data style="font-size:70px;font-family:Roboto,sans-serif;font-weight:900;width:263px;letter-spacing: -7px;color:#bf272d">$560</data>
              <data style="font-size:80px;font-family:Roboto,sans-serif;font-weight:900;width:263px;letter-spacing: -7px;color:#bf272d">billion</data>
              <blockquote style="font-family:Roboto;font-size:24px;line-height:24px;">Lost in India due to air pollution.</blockquote>
            </div>
          </section>
          <section>
            <div class="content" style="background-color:white;">
              <data style="font-size:80px;font-family:Roboto,sans-serif;font-weight:900;width:263px;letter-spacing: -9px;color:#bf272d">80k</data>
              <blockquote style="font-family:Roboto;font-size:24px;line-height:24px;">Trucks plying daily.</blockquote>
            </div>
          </section>
          <section>
            <div class="content" style="background-color:white;">
              <data style="font-size:80px;font-family:Roboto,sans-serif;font-weight:900;width:263px;letter-spacing: -9px;color:#bf272d">20+</data>
              <blockquote style="font-family:Roboto;font-size:24px;line-height:24px;">Cigarettes you smoke if you live in Delhi.</blockquote>
              <section>
              </section>
            </div>
        </div>
          </section>
      </div>
      <!-- CTA -->
      <section class="wrapper" style="padding-top:1em;">
	      <h2 style="color:#00a79b;"><center>We have multiple ways to protect you</center></h2><br/>
        <div class="row" style="padding-bottom:20px;">
          <div id="f1" class="column col-md-2 col-xs-8 col-xs-offset-2 centered">
            <img src="{% static 'home/images/bar-chart.png' %}" alt="Snow" style="width:100%">
            <br />
            <h5><b style="font-weight:bold;color:#00a79b;font-weight:20px;">Real time forecasting</b></h5>
	    <p style="font-weight:bold;color:#00a79b;font-weight:10px;text-align:justify;">We provide air pollution information upto 24 hours in advance as well as historical data to 
	    understand causes and effects</p>
          </div>
          <div id="f2" class="column col-md-2 col-xs-8 col-md-offset-1 col-xs-offset-2 centered">
            <img src="{% static 'home/images/pie-chart.png' %}" alt="Snow" style="width:100%;">
            <br />
            <h5><b style="font-weight:bold;color:#00a79b;font-weight:20px;">Real time graphs</b></h5>
	    <p style="font-weight:bold;color:#00a79b;font-weight:10px;text-align:justify">We display real time and future graphs for air pollutants to help you understand the change and effects.</p>
          </div>
          <div id="f3" class="column col-md-2 col-xs-8 col-md-offset-1 col-xs-offset-2 centered">
            <img src="{% static 'home/images/finance.png' %}" alt="Snow" style="width:100%;;">
            <h5><b style="font-weight:bold;color:#00a79b;font-weight:20px;">Source Identification</b></center></h5>
	    <p style="font-weight:bold;color:#00a79b;font-weight:10px;text-align:justify">We provide the source of pollution and different ways for protecting you.</p>
          </div>
        </div>
      </section>

      {% endblock %}

website/templates/home/map.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<body>

    <h1 style="color:#00a79b;font-size:56px;"><center>Air Quality Map<br \>
        <b style="font-weight:bold;color:#00a79b;font-weight:20px;">Pollution in Real-time</b></center>
    </h1>
    <div style="padding-left:10px;padding-right:10px;">
      <p>
      Air pollution is dynamic and changes throughout the day and even from street to street depending on many conditions.
      This air pollution map helps you understand where air pollution is better and worse, with key air pollutants.
      You can also get to know the air pollutant sources, their health effects, health recommendations, air pollution forecast,
      and air quality over the last day by clicking on those locations.
      </p>
    </div>

<div id="map" class="z-depth-2" style="width:90%;height:400px;margin-left:auto; margin-right:auto;"></div>

<script>
	function myMap() { 
	var locations = [
         ['RK Puram', 28.566008, 77.176743,0, 'http://35.229.111.190:8000/home/details/RK%20Puram', 'PM 2.5'],
         ['Mandir Marg', 28.633845,77.200235,1, 'http://35.229.111.190:8000/home/details/Mandir%20Marg','PM 2.5'],
         ['Punjabi Bagh', 28.661975, 77.124156,2, 'http://35.229.111.190:8000/home/details/Punjabi%20Bagh','PM 2.5'],
         ['Okhla', 28.560280,77.291332 ,3, 'http://35.229.111.190:8000/home/details/Okhla','PM 2.5'],
         ['Rohini',28.749472,77.056533 ,4, 'http://35.229.111.190:8000/home/details/Rohini','PM 2.5']

 ];

	var locations1 = [
         new google.maps.LatLng(28.566008, 77.176743),
          new google.maps.LatLng(28.633845,77.200235),
         new google.maps.LatLng(28.661975, 77.124156),
          new google.maps.LatLng(28.560280,77.291332),
         new google.maps.LatLng(28.749472,77.056533)

 ];


var map = new google.maps.Map(document.getElementById('map'), {
  zoom: 10,
 center: new google.maps.LatLng(28.704059, 77.102490),
 mapTypeId: google.maps.MapTypeId.ROADMAP
});

var infowindow = new google.maps.InfoWindow();

var marker, i;

for (i = 0; i < locations.length; i++) {
  marker = new google.maps.Marker({
   position: new google.maps.LatLng(locations[i][1], locations[i][2]),
   map: map,
  title: locations[i][0],
   url: locations[i][4],
	  icon: {
		  labelOrigin: new google.maps.Point(40,15),
		  url: "{% static 'home/images/map-icon.png' %}",
	  },
  label: { color: '#e53935', fontWeight: 'bold', fontSize: '15px', text: locations[i][0]}
  });

 google.maps.event.addListener(marker, 'mouseover', (function(marker, i) {
   return function() {
     infowindow.setContent(locations[i][5]);
     infowindow.open(map, marker);
   }
 })(marker, i));

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
   return function() {
     infowindow.setContent(locations[i][5]);
     infowindow.open(map, marker);
     window.location.href = this.url;
   }
 })(marker, i));

    }

 var pointArray = new google.maps.MVCArray(locations1);

  // what data for the heatmap and how to display it
  heatmap = new google.maps.visualization.HeatmapLayer({
    data: pointArray,
    radius: 50
  });

  // placing the heatmap on the map
  heatmap.setMap(map);
}
</script>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDCNcNYY-A2pG1C11bNn7Qv7I_Y-dELrQQ&callback=myMap&libraries=visualization"></script>
</body>
 {% endblock %}